(define (problem p05-use-twice)
 (:domain entertainment)
 (:objects
  simple-dvd-1 simple-dvd-2 simple-dvd-3 simple-tv-1 multi-scart-1 scart-cable-1 scart-cable-2 scart-cable-3 scart-cable-4 - equipment
  simple-dvd-1-scart-1 simple-dvd-2-scart-1 simple-dvd-3-scart-1 simple-tv-1-scart-1 multi-scart-1-scart-1 multi-scart-1-scart-2 multi-scart-1-scart-3 multi-scart-1-scart-4 scart-cable-1-scart-1 scart-cable-1-scart-2 scart-cable-2-scart-1 scart-cable-2-scart-2 scart-cable-3-scart-1 scart-cable-3-scart-2 scart-cable-4-scart-1 scart-cable-4-scart-2 - connector
 )
 (:htn
  :ordered-tasks (and
     (av_connect simple-dvd-1 simple-tv-1)
     (av_connect simple-dvd-2 simple-tv-1)
     (av_connect simple-dvd-3 simple-tv-1)
   )
  :ordering ( )
  :constraints ( ))
 (:init
  ;; device simple-dvd-1
  (conn_of simple-dvd-1 simple-dvd-1-scart-1)
  (unused simple-dvd-1-scart-1)
  (out_connector simple-dvd-1-scart-1)
  (audio_connector simple-dvd-1-scart-1)
  (video_connector simple-dvd-1-scart-1)

  ;; device simple-dvd-2
  (conn_of simple-dvd-2 simple-dvd-2-scart-1)
  (unused simple-dvd-2-scart-1)
  (out_connector simple-dvd-2-scart-1)
  (audio_connector simple-dvd-2-scart-1)
  (video_connector simple-dvd-2-scart-1)

  ;; device simple-dvd-3
  (conn_of simple-dvd-3 simple-dvd-3-scart-1)
  (unused simple-dvd-3-scart-1)
  (out_connector simple-dvd-3-scart-1)
  (audio_connector simple-dvd-3-scart-1)
  (video_connector simple-dvd-3-scart-1)

  ;; device simple-tv-1
  (conn_of simple-tv-1 simple-tv-1-scart-1)
  (unused simple-tv-1-scart-1)
  (in_connector simple-tv-1-scart-1)
  (audio_connector simple-tv-1-scart-1)
  (video_connector simple-tv-1-scart-1)

  ;; device multi-scart-1
  (conn_of multi-scart-1 multi-scart-1-scart-1)
  (unused multi-scart-1-scart-1)
  (out_connector multi-scart-1-scart-1)
  (audio_connector multi-scart-1-scart-1)
  (video_connector multi-scart-1-scart-1)
  (conn_of multi-scart-1 multi-scart-1-scart-2)
  (unused multi-scart-1-scart-2)
  (in_connector multi-scart-1-scart-2)
  (audio_connector multi-scart-1-scart-2)
  (video_connector multi-scart-1-scart-2)
  (conn_of multi-scart-1 multi-scart-1-scart-3)
  (unused multi-scart-1-scart-3)
  (in_connector multi-scart-1-scart-3)
  (audio_connector multi-scart-1-scart-3)
  (video_connector multi-scart-1-scart-3)
  (conn_of multi-scart-1 multi-scart-1-scart-4)
  (unused multi-scart-1-scart-4)
  (in_connector multi-scart-1-scart-4)
  (audio_connector multi-scart-1-scart-4)
  (video_connector multi-scart-1-scart-4)

  ;; device scart-cable-1
  (conn_of scart-cable-1 scart-cable-1-scart-1)
  (unused scart-cable-1-scart-1)
  (in_connector scart-cable-1-scart-1)
  (audio_connector scart-cable-1-scart-1)
  (video_connector scart-cable-1-scart-1)
  (conn_of scart-cable-1 scart-cable-1-scart-2)
  (unused scart-cable-1-scart-2)
  (out_connector scart-cable-1-scart-2)
  (audio_connector scart-cable-1-scart-2)
  (video_connector scart-cable-1-scart-2)

  ;; device scart-cable-2
  (conn_of scart-cable-2 scart-cable-2-scart-1)
  (unused scart-cable-2-scart-1)
  (in_connector scart-cable-2-scart-1)
  (audio_connector scart-cable-2-scart-1)
  (video_connector scart-cable-2-scart-1)
  (conn_of scart-cable-2 scart-cable-2-scart-2)
  (unused scart-cable-2-scart-2)
  (out_connector scart-cable-2-scart-2)
  (audio_connector scart-cable-2-scart-2)
  (video_connector scart-cable-2-scart-2)

  ;; device scart-cable-3
  (conn_of scart-cable-3 scart-cable-3-scart-1)
  (unused scart-cable-3-scart-1)
  (in_connector scart-cable-3-scart-1)
  (audio_connector scart-cable-3-scart-1)
  (video_connector scart-cable-3-scart-1)
  (conn_of scart-cable-3 scart-cable-3-scart-2)
  (unused scart-cable-3-scart-2)
  (out_connector scart-cable-3-scart-2)
  (audio_connector scart-cable-3-scart-2)
  (video_connector scart-cable-3-scart-2)

  ;; device scart-cable-4
  (conn_of scart-cable-4 scart-cable-4-scart-1)
  (unused scart-cable-4-scart-1)
  (in_connector scart-cable-4-scart-1)
  (audio_connector scart-cable-4-scart-1)
  (video_connector scart-cable-4-scart-1)
  (conn_of scart-cable-4 scart-cable-4-scart-2)
  (unused scart-cable-4-scart-2)
  (out_connector scart-cable-4-scart-2)
  (audio_connector scart-cable-4-scart-2)
  (video_connector scart-cable-4-scart-2)

  ;; compatibility of connections
  (compatible simple-dvd-1-scart-1 scart-cable-1-scart-1)
  (compatible simple-dvd-1-scart-1 scart-cable-1-scart-2)
  (compatible simple-dvd-1-scart-1 scart-cable-2-scart-1)
  (compatible simple-dvd-1-scart-1 scart-cable-2-scart-2)
  (compatible simple-dvd-1-scart-1 scart-cable-3-scart-1)
  (compatible simple-dvd-1-scart-1 scart-cable-3-scart-2)
  (compatible simple-dvd-1-scart-1 scart-cable-4-scart-1)
  (compatible simple-dvd-1-scart-1 scart-cable-4-scart-2)
  (compatible simple-dvd-2-scart-1 scart-cable-1-scart-1)
  (compatible simple-dvd-2-scart-1 scart-cable-1-scart-2)
  (compatible simple-dvd-2-scart-1 scart-cable-2-scart-1)
  (compatible simple-dvd-2-scart-1 scart-cable-2-scart-2)
  (compatible simple-dvd-2-scart-1 scart-cable-3-scart-1)
  (compatible simple-dvd-2-scart-1 scart-cable-3-scart-2)
  (compatible simple-dvd-2-scart-1 scart-cable-4-scart-1)
  (compatible simple-dvd-2-scart-1 scart-cable-4-scart-2)
  (compatible simple-dvd-3-scart-1 scart-cable-1-scart-1)
  (compatible simple-dvd-3-scart-1 scart-cable-1-scart-2)
  (compatible simple-dvd-3-scart-1 scart-cable-2-scart-1)
  (compatible simple-dvd-3-scart-1 scart-cable-2-scart-2)
  (compatible simple-dvd-3-scart-1 scart-cable-3-scart-1)
  (compatible simple-dvd-3-scart-1 scart-cable-3-scart-2)
  (compatible simple-dvd-3-scart-1 scart-cable-4-scart-1)
  (compatible simple-dvd-3-scart-1 scart-cable-4-scart-2)
  (compatible simple-tv-1-scart-1 scart-cable-1-scart-1)
  (compatible simple-tv-1-scart-1 scart-cable-1-scart-2)
  (compatible simple-tv-1-scart-1 scart-cable-2-scart-1)
  (compatible simple-tv-1-scart-1 scart-cable-2-scart-2)
  (compatible simple-tv-1-scart-1 scart-cable-3-scart-1)
  (compatible simple-tv-1-scart-1 scart-cable-3-scart-2)
  (compatible simple-tv-1-scart-1 scart-cable-4-scart-1)
  (compatible simple-tv-1-scart-1 scart-cable-4-scart-2)
  (compatible multi-scart-1-scart-1 scart-cable-1-scart-1)
  (compatible multi-scart-1-scart-1 scart-cable-1-scart-2)
  (compatible multi-scart-1-scart-1 scart-cable-2-scart-1)
  (compatible multi-scart-1-scart-1 scart-cable-2-scart-2)
  (compatible multi-scart-1-scart-1 scart-cable-3-scart-1)
  (compatible multi-scart-1-scart-1 scart-cable-3-scart-2)
  (compatible multi-scart-1-scart-1 scart-cable-4-scart-1)
  (compatible multi-scart-1-scart-1 scart-cable-4-scart-2)
  (compatible multi-scart-1-scart-2 scart-cable-1-scart-1)
  (compatible multi-scart-1-scart-2 scart-cable-1-scart-2)
  (compatible multi-scart-1-scart-2 scart-cable-2-scart-1)
  (compatible multi-scart-1-scart-2 scart-cable-2-scart-2)
  (compatible multi-scart-1-scart-2 scart-cable-3-scart-1)
  (compatible multi-scart-1-scart-2 scart-cable-3-scart-2)
  (compatible multi-scart-1-scart-2 scart-cable-4-scart-1)
  (compatible multi-scart-1-scart-2 scart-cable-4-scart-2)
  (compatible multi-scart-1-scart-3 scart-cable-1-scart-1)
  (compatible multi-scart-1-scart-3 scart-cable-1-scart-2)
  (compatible multi-scart-1-scart-3 scart-cable-2-scart-1)
  (compatible multi-scart-1-scart-3 scart-cable-2-scart-2)
  (compatible multi-scart-1-scart-3 scart-cable-3-scart-1)
  (compatible multi-scart-1-scart-3 scart-cable-3-scart-2)
  (compatible multi-scart-1-scart-3 scart-cable-4-scart-1)
  (compatible multi-scart-1-scart-3 scart-cable-4-scart-2)
  (compatible multi-scart-1-scart-4 scart-cable-1-scart-1)
  (compatible multi-scart-1-scart-4 scart-cable-1-scart-2)
  (compatible multi-scart-1-scart-4 scart-cable-2-scart-1)
  (compatible multi-scart-1-scart-4 scart-cable-2-scart-2)
  (compatible multi-scart-1-scart-4 scart-cable-3-scart-1)
  (compatible multi-scart-1-scart-4 scart-cable-3-scart-2)
  (compatible multi-scart-1-scart-4 scart-cable-4-scart-1)
  (compatible multi-scart-1-scart-4 scart-cable-4-scart-2)
  (compatible scart-cable-1-scart-1 simple-dvd-1-scart-1)
  (compatible scart-cable-1-scart-1 simple-dvd-2-scart-1)
  (compatible scart-cable-1-scart-1 simple-dvd-3-scart-1)
  (compatible scart-cable-1-scart-1 simple-tv-1-scart-1)
  (compatible scart-cable-1-scart-1 multi-scart-1-scart-1)
  (compatible scart-cable-1-scart-1 multi-scart-1-scart-2)
  (compatible scart-cable-1-scart-1 multi-scart-1-scart-3)
  (compatible scart-cable-1-scart-1 multi-scart-1-scart-4)
  (compatible scart-cable-1-scart-2 simple-dvd-1-scart-1)
  (compatible scart-cable-1-scart-2 simple-dvd-2-scart-1)
  (compatible scart-cable-1-scart-2 simple-dvd-3-scart-1)
  (compatible scart-cable-1-scart-2 simple-tv-1-scart-1)
  (compatible scart-cable-1-scart-2 multi-scart-1-scart-1)
  (compatible scart-cable-1-scart-2 multi-scart-1-scart-2)
  (compatible scart-cable-1-scart-2 multi-scart-1-scart-3)
  (compatible scart-cable-1-scart-2 multi-scart-1-scart-4)
  (compatible scart-cable-2-scart-1 simple-dvd-1-scart-1)
  (compatible scart-cable-2-scart-1 simple-dvd-2-scart-1)
  (compatible scart-cable-2-scart-1 simple-dvd-3-scart-1)
  (compatible scart-cable-2-scart-1 simple-tv-1-scart-1)
  (compatible scart-cable-2-scart-1 multi-scart-1-scart-1)
  (compatible scart-cable-2-scart-1 multi-scart-1-scart-2)
  (compatible scart-cable-2-scart-1 multi-scart-1-scart-3)
  (compatible scart-cable-2-scart-1 multi-scart-1-scart-4)
  (compatible scart-cable-2-scart-2 simple-dvd-1-scart-1)
  (compatible scart-cable-2-scart-2 simple-dvd-2-scart-1)
  (compatible scart-cable-2-scart-2 simple-dvd-3-scart-1)
  (compatible scart-cable-2-scart-2 simple-tv-1-scart-1)
  (compatible scart-cable-2-scart-2 multi-scart-1-scart-1)
  (compatible scart-cable-2-scart-2 multi-scart-1-scart-2)
  (compatible scart-cable-2-scart-2 multi-scart-1-scart-3)
  (compatible scart-cable-2-scart-2 multi-scart-1-scart-4)
  (compatible scart-cable-3-scart-1 simple-dvd-1-scart-1)
  (compatible scart-cable-3-scart-1 simple-dvd-2-scart-1)
  (compatible scart-cable-3-scart-1 simple-dvd-3-scart-1)
  (compatible scart-cable-3-scart-1 simple-tv-1-scart-1)
  (compatible scart-cable-3-scart-1 multi-scart-1-scart-1)
  (compatible scart-cable-3-scart-1 multi-scart-1-scart-2)
  (compatible scart-cable-3-scart-1 multi-scart-1-scart-3)
  (compatible scart-cable-3-scart-1 multi-scart-1-scart-4)
  (compatible scart-cable-3-scart-2 simple-dvd-1-scart-1)
  (compatible scart-cable-3-scart-2 simple-dvd-2-scart-1)
  (compatible scart-cable-3-scart-2 simple-dvd-3-scart-1)
  (compatible scart-cable-3-scart-2 simple-tv-1-scart-1)
  (compatible scart-cable-3-scart-2 multi-scart-1-scart-1)
  (compatible scart-cable-3-scart-2 multi-scart-1-scart-2)
  (compatible scart-cable-3-scart-2 multi-scart-1-scart-3)
  (compatible scart-cable-3-scart-2 multi-scart-1-scart-4)
  (compatible scart-cable-4-scart-1 simple-dvd-1-scart-1)
  (compatible scart-cable-4-scart-1 simple-dvd-2-scart-1)
  (compatible scart-cable-4-scart-1 simple-dvd-3-scart-1)
  (compatible scart-cable-4-scart-1 simple-tv-1-scart-1)
  (compatible scart-cable-4-scart-1 multi-scart-1-scart-1)
  (compatible scart-cable-4-scart-1 multi-scart-1-scart-2)
  (compatible scart-cable-4-scart-1 multi-scart-1-scart-3)
  (compatible scart-cable-4-scart-1 multi-scart-1-scart-4)
  (compatible scart-cable-4-scart-2 simple-dvd-1-scart-1)
  (compatible scart-cable-4-scart-2 simple-dvd-2-scart-1)
  (compatible scart-cable-4-scart-2 simple-dvd-3-scart-1)
  (compatible scart-cable-4-scart-2 simple-tv-1-scart-1)
  (compatible scart-cable-4-scart-2 multi-scart-1-scart-1)
  (compatible scart-cable-4-scart-2 multi-scart-1-scart-2)
  (compatible scart-cable-4-scart-2 multi-scart-1-scart-3)
  (compatible scart-cable-4-scart-2 multi-scart-1-scart-4)
 )
)
